In [1]:
!pip install numpy

In [2]:
import numpy as np
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
np_array1=np.arange(size)
np_array2=np.arange(size)
import time
start=time.time()
result_list =[x+y for x,y in zip(list1,list2)]
end=time.time()
print("list sum time",end-start)
#Numpy arrays
start=time.time()
result_array=np_array1+np_array2
end=time.time()
print("numpy array sum time",end-start)

list sum time 0.12794041633605957
numpy array sum time 0.006438255310058594


In [7]:
my_list = [10,20,30]
arr=np.array(my_list)

In [11]:
list_of_list = [[5,10,15],[20,25,30],[35,40,45]]
arr1=np.array(list_of_list)

In [6]:
type(np.array(list_of_list))

numpy.ndarray

In [8]:
arr

array([10, 20, 30])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(3,)

In [13]:
arr1.shape

(3, 3)

In [14]:
arr.dtype

dtype('int64')

In [19]:
# Numpy Built in Methods
b=np.arange(0,10,3 , dtype=np.int32)
b.dtype
# difference between arange and range()

dtype('int32')

In [20]:
#create arrays of zeros and ones

In [22]:
a1=np.zeros((2,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
a1=np.ones((2,5))
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# array Indexing
arr

array([10, 20, 30])

In [27]:
print(arr[1])

20


In [28]:
print(arr[0]+arr[1])

30


In [29]:
arr1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr1[0,1]

np.int64(10)

In [32]:
arr1[1,1]

np.int64(25)

In [33]:
# array slicing

In [34]:
a1= np.array([1,2,3,4,5,6,7])
a1[1:5]

array([2, 3, 4, 5])

In [37]:
a1[-3:-1]

array([5, 6])

In [41]:
b1= np.array([[1,2,3,4,5],[6,7,8,9,10]])
b1[0,1:4]

array([2, 3, 4])

In [39]:
b1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
b1[0:3,2]

array([3, 8])

In [46]:
b1[0:2,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [47]:
# copy and view
a1

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
x = a1.copy()
x[0] = 42

print(a1)
print(x)

[1 2 3 4 5 6 7]
[42  2  3  4  5  6  7]


In [49]:
y = a1.view()
y[0] = 42

print(a1)
print(y)

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


In [50]:
a1

array([42,  2,  3,  4,  5,  6,  7])

In [51]:
z=a1

In [52]:
z[0]=52

In [53]:
z

array([52,  2,  3,  4,  5,  6,  7])

In [54]:
a1

array([52,  2,  3,  4,  5,  6,  7])

In [56]:
!pip install pandas

In [57]:
import pandas as pd

In [58]:
df=pd.read_csv('italy-covid-daywise.csv')

In [59]:
df

date  new_cases  new_deaths  new_tests
0    31-12-2019          0           0        NaN
1    01-01-2020          0           0        NaN
2    02-01-2020          0           0        NaN
3    03-01-2020          0           0        NaN
4    04-01-2020          0           0        NaN
..          ...        ...         ...        ...
243  30-08-2020       1444           1    53541.0
244  31-08-2020       1365           4    42583.0
245  01-09-2020        996           6    54395.0
246  02-09-2020        975           8        NaN
247  03-09-2020       1326           6        NaN

[248 rows x 4 columns]

In [60]:
type(df)

pandas.core.frame.DataFrame

In [62]:
df.head(10)

date  new_cases  new_deaths  new_tests
0  31-12-2019          0           0        NaN
1  01-01-2020          0           0        NaN
2  02-01-2020          0           0        NaN
3  03-01-2020          0           0        NaN
4  04-01-2020          0           0        NaN
5  05-01-2020          0           0        NaN
6  06-01-2020          0           0        NaN
7  07-01-2020          0           0        NaN
8  08-01-2020          0           0        NaN
9  09-01-2020          0           0        NaN

In [64]:
df.tail(10)

date  new_cases  new_deaths  new_tests
238  25-08-2020        953           4    45798.0
239  26-08-2020        876           4    58054.0
240  27-08-2020       1366          13    57640.0
241  28-08-2020       1409           5    65135.0
242  29-08-2020       1460           9    64294.0
243  30-08-2020       1444           1    53541.0
244  31-08-2020       1365           4    42583.0
245  01-09-2020        996           6    54395.0
246  02-09-2020        975           8        NaN
247  03-09-2020       1326           6        NaN

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   date        248 non-null    object 
 1   new_cases   248 non-null    int64  
 2   new_deaths  248 non-null    int64  
 3   new_tests   135 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 7.9+ KB


In [66]:
df.describe()

new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [67]:
df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [68]:
df.shape

(248, 4)

In [69]:
df.head()

date  new_cases  new_deaths  new_tests
0  31-12-2019          0           0        NaN
1  01-01-2020          0           0        NaN
2  02-01-2020          0           0        NaN
3  03-01-2020          0           0        NaN
4  04-01-2020          0           0        NaN

In [70]:
df.new_cases

0         0
1         0
2         0
3         0
4         0
       ... 
243    1444
244    1365
245     996
246     975
247    1326
Name: new_cases, Length: 248, dtype: int64

In [71]:
df['new_cases']

0         0
1         0
2         0
3         0
4         0
       ... 
243    1444
244    1365
245     996
246     975
247    1326
Name: new_cases, Length: 248, dtype: int64

In [ ]:
df['new_tests','new'] and df.new_cases